### ISSUE TITLE
readthedocs integration failing

### ISSUE THREAD

**Issue by wholmgren** [openpvtools/openpvtools#16]
I logged into readthedocs and saw this alert:

> The project openpvtools doesn't have a valid webhook set up, commits won't trigger new builds for this project. See [the project integrations](https://readthedocs.org/dashboard/openpvtools/integrations/) for more information.

haven't investigated

**Comment by kandersolar** [comment]
I'm not immediately seeing that warning anywhere myself.  The github integration page shows it functioning as expected, including a trigger just now for #17.  🤷

**Comment by wholmgren** [comment]
Interesting! I'll assume I can ignore it and get on with life.
